export default [
    {
        "menu":"用户管理",
        "sub_menu":[
            {
                "href":"#/signin",
                "title":"新增用户"
            },
            {
                "href":"#/get/userlist",
                "title":"用户列表"
            }
        ]
    },{
        "menu":"图书管理",
        "sub_menu":[
            {
                "href":"#/booklist",
                "title":"全部书籍"
            },{
                "href":"#/createbook",
                "title":"添加图书"
            } 
        ]
    },{
        "menu":"日志管理",
        "sub_menu":[
            {
                "href":"#/booklist",
                "title":"我的日志"
            },{
                "href":"#/createbook",
                "title":"全部日志"
            }
        ]
    },{
        "menu":"图书分类",
        "sub_menu":[
            {
                "href":"#/booklist",
                "title":"分类列表"
            }
        ]
    }
]